In [1]:
import sys
from pathlib import Path
current_file=Path(r'D:\projects\easyquant\tests\datareader.ipynb')
sys.path.append(current_file.parent.parent.__str__())

In [2]:
from easydata.configs.url import LOCAL
from easydata.apis.base import BaseReader
my = BaseReader(config=LOCAL,symbol_col='code',date_col='date')

In [3]:
my.get_all_fields()

    datname
0  postgres
1   finance
2    market
3  factorDB

In [4]:
my['finance'].get_all_fields()

0            valuation
1           price_post
2              auction
3    price_post_minute
4     index_conponents
5              balance
6          index_price
7               income
8             cashflow
Name: table_name, dtype: object

In [5]:
my['finance']['valuation'].get_all_fields()

0                       date
1                       code
2                   pe_ratio
3             turnover_ratio
4                   pb_ratio
5                   ps_ratio
6                  pcf_ratio
7             capitalization
8                 market_cap
9            circulating_cap
10    circulating_market_cap
11              pe_ratio_lyr
Name: field, dtype: object

In [6]:
get_valuation = BaseReader(config=my['finance']['valuation'].config,symbol_col='code',date_col='date')

In [7]:
get_valuation(start_date='2022-01-01',end_date='2022-12-31')

                        pe_ratio  turnover_ratio  pb_ratio  ps_ratio  \
date       code
2022-01-04 000001.XSHE    9.0650          0.6025    1.0138    1.9693
           000002.XSHE    6.2127          2.0038    1.0465    0.5304
           000004.XSHE   76.2118          3.9702    2.0922   10.4032
           000005.XSHE  -15.0818          1.3823    1.7408    5.2840
           000006.XSHE    6.6746          0.9409    0.7977    1.6831
...                          ...             ...       ...       ...
2022-12-30 688799.XSHG   16.4371          1.8482    1.9413    2.3560
           688800.XSHG   50.4120          2.9880    6.5970    8.2311
           688819.XSHG   20.6597          0.8826    2.7210    0.8502
           688981.XSHG   25.4232          0.3086    2.4512    6.7785
           689009.XSHG   52.2658          0.5119    4.5437    2.2702

                        pcf_ratio  capitalization  market_cap  \
date       code
2022-01-04 000001.XSHE   -17.6832    1.940592e+06   3233.0259
           000002.XSHE    -8.3625    1.162538e+06   2382.0410
           000004.XSHE  -162.3143    1.560030e+04     31.1850
           000005.XSHE    32.0880    1.058537e+05     24.9815
           000006.XSHE    -3.8939    1.349995e+05     61.1548
...                           ...             ...         ...
2022-12-30 688799.XSHG    22.2776    9.380000e+03     29.8565
           688800.XSHG    13.8427    1.131571e+04    120.7159
           688819.XSHG  -983.4968    9.721000e+04    357.1495
           688981.XSHG    61.3202    7.912665e+05   3255.2703
           689009.XSHG    14.7436    7.129831e+04    217.3886

                        circulating_cap  circulating_market_cap  pe_ratio_lyr
date       code
2022-01-04 000001.XSHE     1.940576e+06               3232.9988       11.1761
           000002.XSHE     9.717553e+05               1991.1267        5.7377
           000004.XSHE     1.163308e+04                 23.2545       48.2567
           000005.XSHE     1.057946e+05                 24.9675       -6.4474
           000006.XSHE     1.349995e+05                 61.1548        7.0729
...                                 ...                     ...           ...
2022-12-30 688799.XSHG     5.531300e+03                 17.6061       18.5720
           688800.XSHG     7.097800e+03                 75.7193      106.0177
           688819.XSHG     1.300754e+04                 47.7897       26.0814
           688981.XSHG     1.957403e+05                805.2755       30.3293
           689009.XSHG     5.117004e+04                156.0175       52.9443

[1149235 rows x 10 columns]